[package]
name = "translate"
version = "0.1.0"
authors = ["Thomas Alcala Schneider <thomas.alcala@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
